### ISSUE TITLE
how to convert private key string to AsymmetricKeyParameter with SM2 algorithm

### ISSUE THREAD

**Issue by bian8021** [bcgit/bc-csharp#432] opened 2023-03-22 02:07 UTC
I used following code to generate CSR and private key, here- I have 2 questions:

1. is this the right code to generate CSR and private key? sm2Parameters variable has been initialized.
2. if we want to use the private key string, we have to covert it to AsymmetricKeyParameter, how to convert it?

    // Generate an SM2 key pair
    var sm2KeyPairGenerator = new ECKeyPairGenerator();
    var sm2KeyGenerationParameters = new ECKeyGenerationParameters(sm2Parameters, new SecureRandom());
    sm2KeyPairGenerator.Init(sm2KeyGenerationParameters);
    var sm2KeyPair = sm2KeyPairGenerator.GenerateKeyPair();

    // Create a PKCS#10 certificate signing request (CSR) for the public key
    var subjectName = new X509Name($"CN={commonName}, C={country}, ST={state}, L={city}, O={organization}, OU={unit}, E={email}");
    var pkcs10CertificationRequest = new Pkcs10CertificationRequest(GMObjectIdentifiers.sm2sign_with_sm3.Id, subjectName, sm2KeyPair.Public, null, sm2KeyPair.Private);

    // Save the CSR to a file
    using (var csrFileWriter = new StreamWriter("csr.pem"))
    {
        var pemWriter = new PemWriter(csrFileWriter);
        pemWriter.WriteObject(pkcs10CertificationRequest);
        pemWriter.Writer.Flush();
    }
    string csr = Convert.ToBase64String(pkcs10CertificationRequest.GetEncoded());

    var pkInfo = PrivateKeyInfoFactory.CreatePrivateKeyInfo(sm2KeyPair.Private);
    string privateKey = Convert.ToBase64String(pkInfo.GetDerEncoded());

**Comment by bian8021** [comment] 2023-03-23 02:12
any comments for the question?

**Comment by peterdettman** [comment] 2023-03-24 04:21
Seems to be essentially a duplicate of https://github.com/bcgit/bc-csharp/issues/435 .

**Closed by peterdettman** 2023-03-24 04:21 UTC
