### ISSUE TITLE
InvalidCastException when parsing a code sign p7b

### ISSUE THREAD

**Issue by acoder84** [bcgit/bc-csharp#310] opened 2021-08-02 14:46 UTC
```
 var p7b = File.ReadAllBytes(path);
 var cmsSignedData = new Org.BouncyCastle.Cms.CmsSignedData(p7b);
```
System.InvalidCastException: Unable to cast object of type 'Org.BouncyCastle.Asn1.DerSequence' to type 'Org.BouncyCastle.Asn1.Asn1OctetString'.
at Org.BouncyCastle.Cms.CmsSignedData..ctor(ContentInfo sigData) in /crypto/src/cms/CMSSignedData.cs:line 138
at Org.BouncyCastle.Cms.CmsSignedData..ctor(Byte[] sigBlock) in /crypto/src/cms/CMSSignedData.cs:line 62

https://github.com/bcgit/bc-csharp/blob/42f933608f60af7e9c36ffa3f9150b06b842a6ca/crypto/src/cms/CMSSignedData.cs#L138

Consider checking the type of signedData.EncapContentInfo.Content before casting.

File for test (rename to .p7b)
[BouncyCastle.Crypto.zip](https://github.com/bcgit/bc-csharp/files/6917717/BouncyCastle.Crypto.zip)

**Comment by cristianst85** [comment] 2021-12-22 00:51
This issue seems to be a duplicate of https://github.com/bcgit/bc-csharp/issues/232.

**Closed** 2024-02-12 17:39 UTC
