### ISSUE TITLE
Asn1IntegerTest fails 

### ISSUE THREAD

**Issue by oznetmaster** [bcgit/bc-csharp#219] opened 2019-11-27 02:57 UTC
https://github.com/bcgit/bc-csharp/blob/7248688e6f513cbdde1ccc1d39904cb964b0c88a/crypto/test/src/asn1/test/ASN1IntegerTest.cs#L31

```
Test Name:	TestFunction
Test FullName:	UnitTests.Org.BouncyCastle.Asn1.Tests.Asn1IntegerTest.TestFunction
Test Source:	C:\Projects\GitHub\bc-csharp\crypto\test\src\asn1\test\ASN1IntegerTest.cs : line 359
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	TestFunction
Test Outcome:	Failed
Result StackTrace:	at Org.BouncyCastle.Asn1.Tests.Asn1IntegerTest.TestFunction() in C:\Projects\GitHub\bc-csharp\crypto\test\src\asn1\test\ASN1IntegerTest.cs:line 363
Result Message:	
Expected string length 17 but was 23. Strings differ at index 13.
  Expected: "Asn1Integer: Okay"
  But was:  "Asn1Integer: no message"
  ------------------------^

```

**Comment by cipherboy** [comment] 2024-02-07 13:57
I am unable to reproduce this as of cf1829ba51741d96e67644bd574ca062740145e1 on .NET 6.0; closing as fixed.

**Closed by cipherboy** 2024-02-07 13:57 UTC
