### ISSUE TITLE
itext7 - 'Pkcs12Store' exists in BouncyCastle.Crypto and BouncyCastle.Cryptography in c#

### ISSUE THREAD

**Issue by anki2828** [bcgit/bc-csharp#509] opened 2024-01-03 10:12 UTC
Issue with iText7 PDF Signing in C#

I am encountering the following exception while trying to sign a PDF using iText7 version 8.0.2 in C#. I have also installed the itext7.bouncy-castle-adapter version 8.0.2 package.

Error occured is :The type 'Pkcs12Store' exists in both 'BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942' and 'BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938'

**Comment by cipherboy** [comment] 2024-02-13 20:50
@anki2828 It looks like you have multiple versions of BouncyCastle in your project. :-) The way to resolve this is by consolidating on one library source, and from there on a single version. 

`BouncyCastle.Cryptography` is the official up-to-date one on NuGet. The other one may be `Portable.BouncyCastle` or another distribution, I'm not sure. You'll likely need to update/downgrade your other dependencies and/or track down the right one that has a reference to an older BC C# distribution and see about fixing that.

The exact solution will depend on your project and its dependencies. :-)

Good luck!

---

n.b., this is also a dupe of #455.

**Closed by cipherboy** 2024-02-13 20:50 UTC
