### ISSUE TITLE
why CmsSignedDataGenerator.AddSigner different signatures are generated each time

### ISSUE THREAD

**Issue by zhous712** [bcgit/bc-csharp#337] opened 2021-12-09 05:05 UTC
![图片](https://user-images.githubusercontent.com/9739857/145337722-6ed09ff0-a535-498a-b381-08b8d8202c50.png)

**Comment by cristianst85** [comment] 2021-12-23 00:36
There are two things here.

When you don't call the `AddSigner` method you only are adding the public key certificate to the CMS, which doesn't result in anything useful (no signature within the CMS).

The correct way is to call the `AddSigner` method. The result is different each time because a CMS also includes an arbitrary attribute such as the signing time (1.2.840.113549.1.9.5).

https://www.ietf.org/rfc/rfc3852.txt

You can use an ASN.1 Editor to inspect your result.

![image](https://user-images.githubusercontent.com/12585988/147168324-67147689-cf44-436f-91c1-222a208dc341.png)

**Comment by dghgit** [comment] 2022-01-13 06:37
Yes, that pretty well describes what is going on. Closing as not a bug.

**Closed by dghgit** 2022-01-13 06:37 UTC
