### ISSUE TITLE
Verify digest for Sha256WithRSAEncryption

### ISSUE THREAD

**Issue by xtomas** [bcgit/bc-csharp#78] opened 2017-05-19 08:48 UTC
Hello,

I have problem with SignerInformation.VerifyDigest method. When algorithm equals to RSA there is check for equality of digInfo.AlgorithmID.Algorithm and digestAlgorithm.Algorithm. I don't know why.

In my case digInfo.AlgorithmID.Algorithm is 2.16.840.1.101.3.4.2.1 (SHA-256) and digestAlgorithm.Algorithm is 1.2.840.113549.1.1.11 (Sha256WithRSAEncryption). So check for equality fails end VerifyDigest result is false. But if I comment equality check, Arrays.ConstantTimeAreEqual(digest, sigHash) is true so digest compare is Ok.

I didn't found any informations in RFCs that contains equality check for used algorithms in this case. There is not way to bypass or override this behaviour.

TJ

**Comment by jimsch** [comment] 2017-05-19 10:36
One problem is that 1.2.840.113549.1.1.11 is not  digest algorithm, so there is a problem with how that SingerInfomation was constructed.  The OID is a signature algorithm

**Comment by xtomas** [comment] 2017-05-22 10:52
I agree. Digest algorithms are described in [rfc5754](https://tools.ietf.org/html/rfc5754#page-3).

But I didn't found any RFC related to comparing digest algorithms OID's for this case.

**Comment by jimsch** [comment] 2017-05-22 15:49
Step 3 section 7.2.2 of RC 8017.  This is part of the RSA signature algorithm verification process

**Comment by dghgit** [comment] 2021-05-30 22:10
Closed as not a bug.

**Closed by dghgit** 2021-05-30 22:10 UTC
