### ISSUE TITLE
.NET 7.0 AOT CRASH

### ISSUE THREAD

**Issue by x64bugreport** [bcgit/bc-csharp#500] opened 2023-11-24 02:58 UTC
```
AsymmetricKeyParameter asymmetricKeyParameter = PrivateKeyFactory.DecryptKey(passPhrase.ToCharArray(), Convert.FromBase64String(privateKey));
byte[] bytes = Encoding.UTF8.GetBytes(this.msg.ToString(SaveOptions.DisableFormatting));
ISigner signer = SignerUtilities.GetSigner(X9ObjectIdentifiers.ECDsaWithSha512.Id);
signer.Init(true, asymmetricKeyParameter);
signer.BlockUpdate(bytes, 0, bytes.Length);
byte[] array = signer.GenerateSignature();
```

AOT Publish Will Crash.

```
System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.NotSupportedException: 'Org.BouncyCastle.Security.CipherUtilities+CipherAlgorithm[]' is missing native code or metadata. This can happen for code that is not compatible with trimming or AOT. Inspect and fix trimming and AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Reflection.Runtime.General.TypeUnifier.WithVerifiedTypeHandle(RuntimeArrayTypeInfo, RuntimeTypeInfo) + 0x5b
   at System.Array.InternalCreate(RuntimeType, Int32, Int32*, Int32*) + 0x5c
   at System.Array.CreateInstance(Type, Int32) + 0x46
   at System.RuntimeType.GetEnumValues() + 0x86
   at Org.BouncyCastle.Utilities.Enums.GetEnumValues[TEnum]() + 0x18
   at Org.BouncyCastle.Utilities.Enums.GetArbitraryValue[TEnum]() + 0xa
   at Org.BouncyCastle.Security.CipherUtilities..cctor() + 0x43
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xc6
```

(edited by @cipherboy for clarity)

**Comment by harrison314** [comment] 2023-11-26 09:20
@x64bugreport try AOT in .NET 8 its problem with enum - https://github.com/dotnet/runtime/issues/72140

**Comment by cipherboy** [comment] 2024-02-13 18:00
Closing per last comment. Additionally, cannot reproduce with a RSA key:

```c#
using Org.BouncyCastle.Security;

var passPhrase = "password";
var privateKey = "MIIFHzBJBgkqhkiG9w0BBQ0wPDAbBgkqhkiG9w0BBQwwDgQIpII67Pp5Vs8CAggAMB0GCWCGSAFlAwQBKgQQBpkbyKLxdtlBlp6tm6lZoASCBND/h43o5NNNmTXWHN2+N9ncoFknxohgShAc8WHKMHt0SCEJab8E2IAxVkYFMOMpvi1KVldcveLlg7hcMIDm74pJmvXOW6b0bENvPMOxFadzr9NjO7j5ZT81dwNLz2pBLyiUMYElWl0LVnxKThQFqijJTDPcmTpFwDiUyTxzHxMx4DsoFYQulRBsZbRCAjsFpPM+OrOekSAyQHKMSbHULvcdWCrSDRtKOyCeCPbBA4OzPJFyzep6trhbQii6rkddf9o54/oJut+LMuUblrHE2yMStfW0G5ZyI7AeOxAy1gKG/CQrvFHn/yhtyjkvPa0sYVGtR4pGew+cs9iIsdFknXOf9frJMA2agQZKc4+rf66NPv+dxVecm40HIR3omk7EnxR8s6msXOOn4qnY7qaeaq1M7pKNqCu6eW5560mW6buLpOkpm/kDbr4v9rfCX41b5rIRzOdfAt71FSJcHp6KFNojK86YsNJWYh9pnfDbjEk7346cCIeJVgICGTmL8Tg6TUy9wIB6eKUXmIG3fKjIEp8OzYAU3/ae8vdmZqD12l3v75muRPs4bP1RdjaVrux5Xlq8TkzU21ixWG6Odj7I1jusSUjz16iR29XhLP/HI80GKYQMc2yHWcYQ1YVXyLzhnHYydrqjW5OTKZW01rbe9BC8XlRzKZJ4IOQMfSiZxcdERtImO86Kprl4du7gvWaTUGTyiQ721Q08GfFdVuAnOO/J8stTLv2Ee7ugTeAFA2+qpz2vAo5JIPOmqjNqI2ytPjLRb80B3tSVXT41OodTD4v5YbNpySMDpw2F052Wx37hl2wNxIP98U6aw3ZjJdM/YfLdGOJhdoRTBDAvygRUDi6F56sDvX8bdXDUZURMg+iMx3Noc5G3TB3JpYunm3BL9lwGWesrkDzg3Vs1J/6c4AMhAsw9+5tzvyGEDHnGZRg07K0eyWskDK0/Qb+vjSLOj8+QphM+EPCmugNnXRNoAdslIFoVfrcKruS1/DeSIesXvMd7sj2RH/xYDcAIGzmwbc+Ki4JTPuoZlF3pGMYEYkkYj2KHjJeX7CeUjCmU9Y7/jHp+fzlKsQAMQLVm8bRjDpvLA84RDJRoCPav333FYqRciZzMjfx2f6AJTCT+/8nv+DBiWcRtab1u6f+p1iDUa8bVt0Y8PB71gwAyonmYgp4A3fSilIlKEGsP2Hb4aU9V5vy1EZT0K0PuAY4yxGPmhedLCKdBqOuwQBxsLDP2YmXR5wQOsI0dVE8zogpgOGOEE9RXNAf7QV7pBOPNu4HQLNuZi22dKi+wkyMLsIR5dGEz7uDIaGQMvlprtOA02RON3gBnQTJAp7E/YMd7OldSBShRRGeIDw7yTrLoHwLIYnA5+ZwFLBPnOrnBC47CwgB2X/+ooL8/+yigoajZIIE5RvzuKRQGjC/ZgSHXSHrtmJKGerOR/3+OYYCTctTa3wTPVRc/vB1hZac9OPmnKpeywCJ4Q+jX+ZOhHOM671H6h9fLPd0tSE75gIkSuJqBuLV2TB1cp7BTnrZxLywCxC779lZBTVLctXu60kiIoW46zgEz1dyf22vfMN5ss0ybvBVCl8ROmrVr8ZWObzkj1MUyifDM8Tayd3uZ3SdHPo8L2G24+4bjyVdFjUvrBdzB5dNzAQ==";
var msg = "Alex Was Here";

AsymmetricKeyParameter asymmetricKeyParameter = PrivateKeyFactory.DecryptKey(passPhrase.ToCharArray(), Convert.FromBase64String(privateKey));
byte[] bytes = Encoding.UTF8.GetBytes(msg);
ISigner signer = SignerUtilities.GetSigner(PkcsObjectIdentifiers.Sha256WithRsaEncryption);
signer.Init(true, asymmetricKeyParameter);
signer.BlockUpdate(bytes, 0, bytes.Length);
byte[] array = signer.GenerateSignature();

Console.WriteLine(Convert.ToBase64String(array));
```

via:

```
$ dotnet publish -r linux-amd64 -c Release && ./bin/Release/net7.0/linux-x64/16
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/lib/dotnet/sdk/8.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(251,5): warning NETSDK1201: For projects targeting .NET 8.0 and higher, specifying a RuntimeIdentifier will no longer produce a self contained app by default. To continue building self-contained apps, set the SelfContained property to true or use the --self-contained argument. [/home/ascheel/tmp/16/16.csproj]
  16 -> /home/ascheel/tmp/16/bin/Release/net7.0/linux-x64/16.dll
  Generating native code
  16 -> /home/ascheel/tmp/16/bin/Release/net7.0/linux-x64/publish/
fytbvWxvMm+HdSpnKfqFRoeCvFHEsmsQ8FK6+6yDAfZm2roGD03r5SCxeR2C9PVhq/bYWmS9cecTnDaR3+coVPgGRUkHRn9ZmpNUJ9zy0Qw8tEqAol7fDkHFvPzTCXc99k4FMJjUcEOc0mamCgIH5PN03+5o2FHzjFZoiSP6P/ZwumRjFveldL//ab+5V6/ktlEvdh7D218vj3pCaxX9EaLBMsmkuw9nYYoQ21gISd9VK8Co/3spZGaBWAJs3Ylf2pXBxp5G17AUlaiCSo95YVwcZqiCcRw1bfjf/smHtWXcW5aQAPs3U9iTT7dryAG6CnX/69vZCJO3N3FEw6Z3zQ==
```

Let us know if this is still an issue and we can re-open. And, if possible, a test key would be appreciated. :-)

**Closed by cipherboy** 2024-02-13 18:00 UTC
